
# www.xmisp.com
#
# dockerfile
#

FROM centos:latest
MAINTAINER biaolian@xmisp.com


#RUN curl -fSL http://mirrors.163.com/.help/CentOS6-Base-163.repo -o /etc/yum.repos.d/CentOS6-Base-163.repo
#RUN yum makecache
RUN yum -y install wget curl-devel curl tar gcc gcc-c++ gcc-g77 make libtool autoconf  automake  libxml2 libxml2-devel libtool-ltdl-devel libtool-ltdl libmcrypt libmcrypt-devel libpng libpng-devel libjpeg-devel openssl openssl-devel gd-devel gd cmake
#RUN yum -y install pcre pcre-*
RUN groupadd -g 1051 www && useradd -u 1051 -g www -s /sbin/nologin www

#nginx
#
#
#
RUN set -xe \
    && cd /usr/src \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/freetype-2.1.10.tar.gz -o freetype-2.1.10.tar.gz \
    && tar -zxvf freetype-2.1.10.tar.gz \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/libpng-1.2.50.tar.gz -o libpng-1.2.50.tar.gz \
    && tar -zxvf libpng-1.2.50.tar.gz \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/libevent-1.4.14b.tar.gz -o libevent-1.4.14b.tar.gz \
    && tar -zxvf libevent-1.4.14b.tar.gz \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/libmcrypt-2.5.8.tar.gz -o libmcrypt-2.5.8.tar.gz \
    && tar -zxvf libmcrypt-2.5.8.tar.gz \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/jpegsrc.v6b.tar.gz -o jpegsrc.v6b.tar.gz \
    && tar -zxvf jpegsrc.v6b.tar.gz \
    && curl -fSL http://php.net/distributions/php-5.6.31.tar.gz  -o php-5.6.31.tar.gz \
    && tar -zxvf php-5.6.31.tar.gz \
    && curl -fSL http://pecl.php.net/get/mongo-1.6.14.tgz -o mongo-1.6.14.tgz \
    && tar -zxvf mongo-1.6.14.tgz \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/php_extend/memcache-3.0.6.tgz -o memcache-3.0.6.tgz \
    && tar -zxvf memcache-3.0.6.tgz \
    && curl -fSL http://192.168.61.77/PACKAGE/nginx-1.13.3.tar.gz  -o nginx-1.13.3.tar.gz \
    && tar -zxvf nginx-1.13.3.tar.gz


RUN set -xe \
    && cd /usr/src/freetype-2.1.10 \
    && ./configure --prefix=/usr/local/freetype.2.1.10 && make && make install


RUN set -xe \
    && cd /usr/src/libpng-1.2.50 \
    && ./configure --prefix=/usr/local/libpng.1.2.50 && make && make install


RUN set -xe \
    && cd /usr/src/libevent-1.4.14b \
    && ./configure && make && make install


RUN set -xe \
    && cd /usr/src/libmcrypt-2.5.8 \
    && ./configure --disable-posix-threads && make && make install \
    && /sbin/ldconfig \
    && cd libltdl/ \
    && ./configure --enable-ltdl-install && make && make install


RUN set -xe \
    && cd /usr/src/jpeg-6b \
    && cp -f /usr/share/libtool/config/config.guess . \
    && cp -f /usr/share/libtool/config/config.sub . \
    && mkdir -p /usr/local/jpeg.6/include \
    && mkdir /usr/local/jpeg.6/lib \
    && mkdir /usr/local/jpeg.6/bin \
    && mkdir -p /usr/local/jpeg.6/man/man1 \
    && ./configure --prefix=/usr/local/jpeg.6 --enable-shared --enable-static && make && make install-lib && make install



RUN set -xe \
    && cd /usr/local/ \
    && curl -fSL http://oss.aliyuncs.com/aliyunecs/onekey/pcre-8.12.tar.gz -o pcre-8.12.tar.gz \
    && tar -zxvf pcre-8.12.tar.gz \
    && rm -rf pcre-8.12.tar.gz \
    && cd pcre-8.12 \
    && ./configure  && make && make install



#nginx
RUN set -xe \
    && cd /usr/src/nginx-1.13.3 \
    && ./configure --user=www --group=www --prefix=/xmisp/server/nginx --with-http_gzip_static_module --with-http_ssl_module --without-http-cache --with-http_stub_status_module  --with-http_auth_request_module --with-http_dav_module --with-http_sub_module  --with-pcre=/usr/local/pcre-8.12 \
    && make && make install



RUN set -xe \
    && chown www.www -R /xmisp/server/nginx \
    && mkdir -p /xmisp/www/default/nginx-vhosts \
    && echo "<?php" >/xmisp/www/default/i.php \
    && echo "phpinfo();?>" >>/xmisp/www/default/i.php \
    && chown www.www -R /xmisp/www
RUN mkdir -p /xmisp/logs
COPY nginx.conf /xmisp/server/nginx/conf
COPY default.conf /xmisp/www/default/nginx-vhosts


RUN yum install -y bzip2 bzip2-devel readline-devel

###php5.5
RUN set -xe \
    && echo "/usr/local/lib" >>/etc/ld.so.conf.d/local.conf \
    && ldconfig -v \
    && cd /usr/src/php-5.6.31 \
    && ./configure --prefix=/xmisp/server/php/php-5.6.31 \
        --enable-opcache \
        --with-config-file-path=/xmisp/server/php/php-5.6.31/etc \
        --with-mysql=mysqlnd \
        --with-mysqli=mysqlnd \
        --with-pdo-mysql=mysqlnd \
        --with-fpm-user=www \
        --with-fpm-group=www \
        --with-zlib \
        --with-iconv \
#--with-gd \
        --with-xmlrpc \
        --with-curl \
        --with-mcrypt \
        --with-freetype-dir=/usr/local/freetype.2.1.10 \
        --with-jpeg-dir=/usr/local/jpeg.6 \
        --with-png-dir=/usr/local/libpng.1.2.50 \
        --with-gettext \
        --with-mhash \
        --with-libxml-dir \
        --with-bz2 \
        --with-readline \
        --with-openssl \
        --disable-maintainer-zts \
        --disable-rpath \
        --disable-ipv6 \
        --disable-debug \
        --disable-fileinfo \
        --enable-pcntl \
        --enable-sockets \
        --enable-wddx \
        --enable-zip \
        --enable-calendar \
        --enable-bcmath \
        --enable-soap \
        --enable-shmop \
        --enable-sysvmsg \
        --enable-sysvsem \
        --enable-sysvshm \
        --enable-ftp \
        --enable-mbstring \
        --enable-fpm \
        --enable-static \
        --enable-inline-optimization


RUN set -xe \
    && cd /usr/src/php-5.6.31 \
    && make \
    && make install \
    && cp php.ini-production /xmisp/server/php/php-5.6.31/etc/php.ini

RUN set -xe \
    && sed -i 's#; extension_dir = \"\.\/\"#extension_dir = "/xmisp/server/php/php-5.6.31/lib/php/extensions/no-debug-non-zts-20131226/"#' /xmisp/server/php/php-5.6.31/etc/php.ini \
    && sed -i 's/\;upload_tmp_dir =/upload_tmp_dir =\/xmisp\/www\/default\/temp/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
	&& sed -i 's/post_max_size = 8M/post_max_size = 64M/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
    && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 64M/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
    && sed -i 's/;date.timezone =/date.timezone = PRC/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
    && sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=1/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
    && sed -i 's/max_execution_time = 30/max_execution_time = 300/g' /xmisp/server/php/php-5.6.31/etc/php.ini \
#adjust php-fpm
    && cp /xmisp/server/php/php-5.6.31/etc/php-fpm.conf.default /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,user = nobody,user=www,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,group = nobody,group=www,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,^pm.min_spare_servers = 1,pm.min_spare_servers = 5,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,^pm.max_spare_servers = 3,pm.max_spare_servers = 35,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,^pm.max_children = 5,pm.max_children = 100,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,^pm.start_servers = 2,pm.start_servers = 20,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,;pid = run/php-fpm.pid,pid = run/php-fpm.pid,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,;error_log = log/php-fpm.log,error_log = /xmisp/server/php/php-5.6.31/log/php-fpm.log,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && sed -i 's,;slowlog = log/$pool.log.slow,slowlog = /xmisp/server/php/php-5.6.31/log/\$pool.log.slow,g' /xmisp/server/php/php-5.6.31/etc/php-fpm.conf \
    && mkdir -p /xmisp/server/php/php-5.6.31/log \
    #self start
    && cd /usr/src/php-5.6.31 \
    && install -v -m755 sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm




RUN set -xe \
    && cd /usr/src/mongo-1.6.14 \
    &&  /xmisp/server/php/php-5.6.31/bin/phpize \
    && ./configure --with-php-config=/xmisp/server/php/php-5.6.31/bin/php-config \
    && make && make install \
    && echo "extension=mongo.so" >> /xmisp/server/php/php-5.6.31/etc/php.ini

RUN set -xe \
    && cd /usr/src/memcache-3.0.6 \
    &&  /xmisp/server/php/php-5.6.31/bin/phpize \
    && ./configure --enable-memcache --with-php-config=/xmisp/server/php/php-5.6.31/bin/php-config \
    && make && make install \
    && echo "extension=memcache.so" >> /xmisp/server/php/php-5.6.31/etc/php.ini


RUN set -xe \
    && cd /usr/src/ \
    && curl -fSL https://github.com/phpredis/phpredis/archive/2.2.4.tar.gz -o 2.2.4.tar.gz \
    && tar -zxvf 2.2.4.tar.gz \
    && cd /usr/src/phpredis-2.2.4 \
    &&  /xmisp/server/php/php-5.6.31/bin/phpize \
    && ./configure --with-php-config=/xmisp/server/php/php-5.6.31/bin/php-config \
    && make && make install \
    && echo "extension=redis.so" >> /xmisp/server/php/php-5.6.31/etc/php.ini \
    && chown www.www -R /xmisp/server/php

RUN set -xe \
    && cd /usr/src/php-5.6.31/ext/gd \
    && /xmisp/server/php/php-5.6.31/bin/phpize \
    && ./configure --with-php-config=/xmisp/server/php/php-5.6.31/bin/php-config \
    && make && make install \
    && echo "extension=gd.so" >> /xmisp/server/php/php-5.6.31/etc/php.ini \
    && chown www.www -R /xmisp/server/php

RUN set -xe \
    && yum clean packages \
    && yum clean headers \
    && yum clean all \
    && cd /usr/src/ \
    && rm -rf *

WORKDIR /xmisp/www/default/nginx-vhosts
EXPOSE 80

COPY phprun.sh /root/phprun.sh
RUN chmod +x /root/phprun.sh
CMD ["bash","/root/phprun.sh"]
#容器内启动进程必须是前台运行，后台就以后退出了。
#CMD ["/xmisp/server/nginx/sbin/nginx", "-g", "daemon off;"]

